-- Reference names only: no registrations, accounts, dates of birth or contact details.
INSERT INTO public.registration_references(id,name,title,organization,image) VALUES
('B1','Abednego Nyarkoh-Mensah','Bishop','United Denominations','assets/bishops/001.jpg'),
('B2','Abraham Nii Ayi Aryee','Bishop','United Denominations','assets/bishops/002.jpg'),
('B3','Adedayo Adeyemi Adeniji','Bishop','United Denominations','assets/bishops/matched-3.webp'),
('B4','Adelaide Heward-Mills','Episcopal Sister','United Denominations','assets/bishops/matched-4.webp'),
('B5','Adeolu Adepoju','Bishop','United Denominations','assets/bishops/matched-5.webp'),
('B6','Akwele Ivanna Kiruja','Episcopal Sister','United Denominations','assets/bishops/matched-6.webp'),
('B7','Alexander Gottlieb Kofi-Opata','Bishop','United Denominations','assets/bishops/matched-7.webp'),
('B8','Alfred Adigbo','Bishop','United Denominations','assets/bishops/matched-8.webp'),
('B9','Amelia Aidoo','Episcopal Sister','United Denominations','assets/bishops/matched-9.webp'),
('B199','Andrew Gyamfi','Bishop','First Love','assets/bishops/matched-199.webp'),
('B10','Andrew Kwaku Osei','Bishop','United Denominations','assets/bishops/matched-10.webp'),
('B11','Andrews Osei','Bishop','United Denominations','assets/bishops/matched-11.webp'),
('B12','Andy Agyemang Jumah','Bishop','United Denominations','assets/bishops/012.jpg'),
('B200','Annika Dwimoh','Bishop','First Love','assets/bishops/matched-200.webp'),
('B13','Armstrong Simpson Nartey','Bishop','United Denominations','assets/bishops/matched-13.webp'),
('B14','Augustine Frantz Appiah','Bishop','United Denominations',''),
('B201','Augustine Kunituo','Bishop','First Love','assets/bishops/matched-201.webp'),
('B15','Baffour Kwaku Kyei','Bishop','United Denominations','assets/bishops/015.jpg'),
('B202','Benjamin Fiadonu','Bishop','First Love','assets/bishops/matched-202.webp'),
('B16','Benjamin Kwapong Lokko','Bishop','United Denominations','assets/bishops/matched-16.webp'),
('B17','Bernard Koranteng','Bishop','United Denominations','assets/bishops/matched-17.webp'),
('B319','Brian Masuku','Bishop','Outreach','assets/outreach/brian-masuku.png'),
('B18','Brian Yaw Adu','Bishop','United Denominations','assets/bishops/matched-18.webp'),
('B19','Bridgette-Marian Ogoe','Episcopal Sister','United Denominations','assets/bishops/matched-19.webp'),
('B20','Charles Amoo','Bishop','United Denominations','assets/bishops/matched-20.webp'),
('B203','Christian Agbosu-Agorvor','Bishop','First Love','assets/bishops/matched-203.webp'),
('B21','Christian Ago Mensah','Bishop','United Denominations','assets/bishops/matched-21.webp'),
('B22','Christian Assi Adoupo','Bishop','United Denominations','assets/bishops/022.jpg'),
('B23','Christos Isaac Abbey','Bishop','United Denominations','assets/bishops/matched-23.webp'),
('B24','Clarence Welds','Bishop','United Denominations','assets/bishops/matched-24.webp'),
('B204','Cleland Cofie Bruce','Bishop','First Love','assets/bishops/matched-204.webp'),
('B205','Clement Asante','Bishop','First Love','assets/bishops/matched-205.webp'),
('B206','Daniel Amofah','Bishop','First Love','assets/bishops/matched-206.webp'),
('B26','Daniel Arthur-Baidoo','Bishop','United Denominations','assets/bishops/matched-26.webp'),
('B207','Daniel Fiifi Gyamerah','Bishop','First Love','assets/bishops/matched-207.webp'),
('B27','Daniel Harlley','Bishop','United Denominations','assets/bishops/matched-27.webp'),
('B28','Daniel Kwaku Atiemoh','Bishop','United Denominations','assets/bishops/matched-28.webp'),
('B253','Daniel Marcus','Bishop','First Love','assets/bishops/matched-253.webp'),
('B29','Daniel Odei-Siaw','Bishop','United Denominations','assets/bishops/matched-29.webp'),
('B208','Daniella Hart','Mother','First Love','assets/bishops/matched-208.webp'),
('B30','David Adjah Ashong','Bishop','United Denominations','assets/bishops/030.jpg'),
('B31','David Afreh','Bishop','United Denominations','assets/bishops/031.jpg'),
('B32','David Asomani','Bishop','United Denominations','assets/bishops/matched-32.webp'),
('B33','David Kwaku Asiedu','Bishop','United Denominations','assets/bishops/matched-33.webp'),
('B34','David Ofori Gyedu','Bishop','United Denominations','assets/bishops/matched-34.webp'),
('B35','David Yalleh','Bishop','United Denominations','assets/bishops/matched-35.webp'),
('B36','Dennis Agyei-Gyan','Bishop','United Denominations','assets/bishops/matched-36.webp'),
('B37','Dennis Ampofo Cudjoe','Bishop','United Denominations','assets/bishops/037.jpg'),
('B38','Dennis Djagbletey','Bishop','United Denominations','assets/bishops/matched-38.webp'),
('B39','Eat Sackey','Bishop','United Denominations','assets/bishops/matched-39.webp'),
('B40','Ebenezer Adom Barnor','Bishop','United Denominations','assets/bishops/matched-40.webp'),
('B329','Ebo Ankrah','Bishop','Outreach','assets/outreach/confirmed-329.jpg'),
('B41','Eddie Fabin','Bishop','United Denominations','assets/bishops/eddie-fabin-white.png'),
('B322','Eddy Addy','Bishop','United Denominations','assets/bishops/confirmed-322.jpeg'),
('B42','Eddy Cofie','Bishop','United Denominations','assets/bishops/matched-42.webp'),
('B43','Edward Botwe','Bishop','United Denominations','assets/bishops/matched-43.webp'),
('B44','Edwin Adu-Tutu','Bishop','First Love','assets/bishops/matched-44.webp'),
('B45','Edwin Morgan Ogoe','Bishop','United Denominations','assets/bishops/matched-45.webp'),
('B196','Edwin Morgan Ogoe Jr','Bishop','First Love','assets/bishops/matched-196.webp'),
('B46','Elaine Klufio','Episcopal Sister','United Denominations','assets/bishops/matched-46.webp'),
('B209','Emmanuel Amartey','Bishop','First Love','assets/bishops/matched-209.webp'),
('B48','Emmanuel Ankrah','Bishop','United Denominations','assets/bishops/matched-48.webp'),
('B47','Emmanuel Baiden','Bishop','United Denominations','assets/bishops/matched-47.webp'),
('B49','Emmanuel Bekoe Saforo Sakyi','Bishop','United Denominations','assets/bishops/matched-49.webp'),
('B50','Emmanuel Buernor Alimo','Bishop','United Denominations',''),
('B210','Emmanuel Fosu','Bishop','First Love','assets/bishops/matched-210.webp'),
('B51','Emmanuel Klufio','Bishop','United Denominations','assets/bishops/matched-51.webp'),
('B52','Emmanuel Kofi-Yeboah','Bishop','United Denominations','assets/bishops/matched-52.webp'),
('B53','Emmanuel Kwaku Klutse','Bishop','United Denominations','assets/bishops/053.jpg'),
('B324','Emmanuel Nterful','Bishop','United Denominations','assets/bishops/confirmed-324.jpeg'),
('B211','Emmanuel Opoku Baah','Bishop','First Love','assets/bishops/matched-211.webp'),
('B54','Emmanuel Samuel Baidoo','Bishop','United Denominations','assets/bishops/matched-54.webp'),
('B55','Emmanuel Tetteh','Bishop','United Denominations','assets/bishops/matched-55.webp'),
('B254','Enoch Boakye-Yiadom','Bishop','First Love','assets/bishops/verified-254.webp'),
('B212','Enoch Odartei Lamptey','Bishop','First Love','assets/bishops/matched-212.webp'),
('B213','Enoch Tettey-Angmor','Bishop','First Love','assets/bishops/matched-213.webp'),
('B56','Erasmus Pascal Mensah','Bishop','United Denominations','assets/bishops/matched-56.webp'),
('B57','Eric Kobina Asare','Bishop','United Denominations','assets/bishops/matched-57.webp'),
('B58','Eric Lamptey','Bishop','First Love',''),
('B59','Erica-Luka Aryee','Mother','First Love','assets/bishops/matched-59.webp'),
('B60','Ernest Addai-Duah','Bishop','United Denominations','assets/bishops/matched-60.webp'),
('B61','Ernest Aryee','Bishop','United Denominations','assets/bishops/matched-61.webp'),
('B214','Esme Asha Mantiziba','Bishop','First Love','assets/bishops/matched-214.webp'),
('B215','Farrell N.K.A Bruce','Bishop','First Love','assets/bishops/matched-215.webp'),
('B332','Faustina Carla Boateng','Mother','Outreach','assets/outreach/confirmed-332.jpg'),
('B62','Felix Bediako','Bishop','United Denominations','assets/bishops/matched-62.webp'),
('B247','Foster Boadi','Bishop','First Love',''),
('B63','Foster Sefakor Mensah','Bishop','United Denominations','assets/bishops/063.jpg'),
('B64','Francis Nii Aryee Hammond','Bishop','United Denominations','assets/bishops/matched-64.webp'),
('B65','Francis Okyere','Bishop','United Denominations','assets/bishops/matched-65.webp'),
('B66','Francis Philip Asamoah','Bishop','United Denominations','assets/bishops/matched-66.webp'),
('B67','Francis Tsikata-Akatto','Bishop','United Denominations','assets/bishops/matched-67.webp'),
('B68','Frank Ofori Adjei','Bishop','United Denominations','assets/bishops/matched-68.webp'),
('B216','Frank Opoku','Bishop','First Love','assets/bishops/matched-216.webp'),
('B69','Frank Otchere','Bishop','United Denominations','assets/bishops/confirmed-b69.jpg'),
('B70','Frank Tawiah-Amissah','Bishop','United Denominations','assets/bishops/matched-70.webp'),
('B71','Fred Ansah Quartey','Bishop','United Denominations','assets/bishops/matched-71.webp'),
('B72','Frederick Nortey','Bishop','United Denominations','assets/bishops/matched-72.webp'),
('B73','George Aferi Obeng','Bishop','United Denominations','assets/bishops/matched-73.webp'),
('B331','George Antwi','Bishop','Outreach','assets/outreach/confirmed-331.jpeg'),
('B217','Geraldo Amoa','Bishop','First Love','assets/bishops/matched-217.webp'),
('B328','Gifty Iris Calah Krofuah','Mother','Outreach','assets/outreach/confirmed-328.jpeg'),
('B74','Glen Kwame Opoku','Bishop','First Love','assets/bishops/matched-74.webp'),
('B75','Gustav Offei-Manu','Bishop','United Denominations','assets/bishops/075.jpg'),
('B76','Hamish Oddoye','Bishop','United Denominations','assets/bishops/matched-76.webp'),
('B77','Harry Kwesi Dodd','Bishop','United Denominations','assets/bishops/077.jpg'),
('B78','Henri Fogwe','Bishop','First Love','assets/bishops/matched-78.webp'),
('B79','Henrietta Ariel Orleans-Lindsay','Mother','First Love','assets/bishops/matched-79.webp'),
('B80','Henry Asare-Duah','Bishop','United Denominations','assets/bishops/matched-80.webp'),
('B81','Henry Oti-Frimpong','Bishop','United Denominations','assets/bishops/matched-81.webp'),
('B82','Immanuel Obeng','Bishop','United Denominations','assets/bishops/matched-82.webp'),
('B83','Irene Odei-Siaw','Episcopal Sister','United Denominations','assets/bishops/083.jpg'),
('B218','Isaac Agyeman','Bishop','First Love','assets/bishops/matched-218.webp'),
('B219','Isaac Koranteng','Bishop','First Love','assets/bishops/matched-219.webp'),
('B220','Isaac Nakoja','Bishop','First Love','assets/bishops/matched-220.webp'),
('B326','Isaac OB Commey','Bishop','United Denominations','assets/bishops/confirmed-326.jpeg'),
('B84','Isaac Sappor','Bishop','United Denominations','assets/bishops/matched-84.webp'),
('B85','Isaac Ssali','Bishop','United Denominations','assets/bishops/matched-85.webp'),
('B327','Ishmael Sam','Bishop','United Denominations','assets/bishops/confirmed-327.png'),
('B86','Jacob Etrue Godwyll','Bishop','First Love','assets/bishops/matched-86.webp'),
('B87','Jamel Amponsah-Baa','Bishop','United Denominations','assets/bishops/matched-87.webp'),
('B141','James Quist-Therson','Bishop','First Love','assets/bishops/matched-141.webp'),
('B197','Jane Hyde','Mother','First Love','assets/bishops/matched-197.webp'),
('B88','Jason Kofi Opata','Bishop','United Denominations','assets/bishops/matched-88.webp'),
('B89','Jeffrey Kwame Ocran','Bishop','United Denominations','assets/bishops/matched-89.webp'),
('B221','Jennis Opoku','Bishop','First Love','assets/bishops/matched-221.webp'),
('B90','Jeremy Menyisse','Bishop','United Denominations','assets/bishops/090.jpg'),
('B91','Joe Owusu-Adjei','Bishop','United Denominations','assets/bishops/091.jpg'),
('B92','Joel Obuobisa','Bishop','United Denominations','assets/bishops/matched-92.webp'),
('B93','John Ato Dickson','Bishop','United Denominations','assets/bishops/093.jpg'),
('B94','John Boffah','Bishop','United Denominations','assets/bishops/matched-94.webp'),
('B95','John Yaw Frimpong','Bishop','United Denominations','assets/bishops/095.jpg'),
('B246','Joojo Stephens','Bishop','First Love','assets/bishops/matched-246.webp'),
('B96','Joseph Aboagye','Bishop','United Denominations','assets/bishops/matched-96.webp'),
('B97','Joseph Aryee','Bishop','United Denominations','assets/bishops/matched-97.webp'),
('B98','Joseph Kofi Amable','Bishop','United Denominations','assets/bishops/matched-98.webp'),
('B252','Joseph Odarkwei Mills','Bishop','First Love','assets/bishops/reconciled-252.webp'),
('B99','Joseph Papa Wachirah Kabiro','Bishop','First Love','assets/bishops/matched-99.webp'),
('B100','Joshua Dormediame','Bishop','United Denominations','assets/bishops/100.jpg'),
('B194','Joshua Heward-Mills','Bishop','First Love','assets/bishops/matched-194.webp'),
('B101','Josie Marie Asamoah','Episcopal Sister','United Denominations','assets/bishops/matched-101.webp'),
('B323','Joy Bruce','Episcopal Sister','United Denominations','assets/bishops/confirmed-323.png'),
('B102','Jude Orraca-Tetteh','Bishop','United Denominations','assets/bishops/matched-102.webp'),
('B103','Kakra Baiden','Bishop','United Denominations','assets/bishops/matched-103.webp'),
('B104','Kathleen-Sarah Parker-Allotey','Episcopal Sister','United Denominations','assets/bishops/matched-104.webp'),
('B105','Kenneth Agyei','Bishop','United Denominations','assets/bishops/105.jpg'),
('B106','Kenneth Kissi Bamfo','Bishop','United Denominations','assets/bishops/matched-106.webp'),
('B107','Kenneth Oswald Awutey','Bishop','United Denominations','assets/bishops/107.jpg'),
('B222','Kent Njeru','Bishop','First Love','assets/bishops/matched-222.webp'),
('B108','Khauhelo Mokobocho','Bishop','United Denominations','assets/bishops/matched-108.webp'),
('B195','Kiki Heward-Mills','Mother','First Love','assets/bishops/matched-195.webp'),
('B109','King Bodom Appiagyei','Bishop','United Denominations','assets/bishops/matched-109.webp'),
('B110','Kingsley Gyasi','Bishop','United Denominations','assets/bishops/matched-110.webp'),
('B111','Kodwo K Orleans-Lindsay','Bishop','United Denominations','assets/bishops/111.jpg'),
('B112','Kofi Hene Asare','Bishop','United Denominations','assets/bishops/matched-112.webp'),
('B223','Kojo Yeboah Atiemo','Bishop','First Love','assets/bishops/matched-223.webp'),
('B113','Kristoffer Odoi Yemoh','Bishop','United Denominations','assets/bishops/113.jpg'),
('B114','Kudzo Jonathan Sewornuku Bekui','Bishop','United Denominations','assets/bishops/matched-114.webp'),
('B115','Kwabena Appiah Denkyira','Bishop','United Denominations','assets/bishops/matched-115.webp'),
('B116','Kwabena Asare Asamoa','Bishop','United Denominations','assets/bishops/reconciled-116.webp'),
('B117','Kwabena Junior Asamoah','Bishop','United Denominations','assets/bishops/117.jpg'),
('B118','Kwabena Oware Amoako-Doku','Bishop','United Denominations','assets/bishops/118.jpg'),
('B119','Kwame Adu Gyamfi','Bishop','United Denominations','assets/bishops/matched-119.webp'),
('B120','Kwame Asiedu Owusu','Bishop','United Denominations','assets/bishops/matched-120.webp'),
('B121','Kweku Amonoo-Neizer','Bishop','United Denominations','assets/bishops/matched-121.webp'),
('B122','Kweku Amponsah','Bishop','United Denominations','assets/bishops/matched-122.webp'),
('B123','Kwesi Woode','Bishop','United Denominations','assets/bishops/matched-123.webp'),
('B224','Latisha Freda Appiah Kubi','Bishop','First Love','assets/bishops/matched-224.webp'),
('B320','Leonard Hyde','Bishop','Outreach','assets/outreach/leonard-hyde-red-edited.png'),
('B124','Leonora-Jamie Hyde','Episcopal Sister','United Denominations','assets/bishops/124.jpg'),
('B125','Lilian Hasia Ofosua Commey','Episcopal Sister','United Denominations','assets/bishops/matched-125.webp'),
('B126','Linda Aryee','Episcopal Sister','United Denominations','assets/bishops/126.jpg'),
('B127','Louisa-Timothea Mills-Odoi','Mother','First Love','assets/bishops/matched-127.webp'),
('B128','Lovell Ankrah','Bishop','Outreach','assets/bishops/matched-128.webp'),
('B129','Luke Akwasi Frimpong Mensah','Bishop','United Denominations','assets/bishops/129.jpg'),
('B130','Marcel Aboagye','Bishop','Outreach','assets/bishops/matched-130.webp'),
('B226','Maxwell Manu','Bishop','First Love','assets/bishops/matched-226.webp'),
('B131','Mcivin Afetseng Mafora','Bishop','United Denominations','assets/bishops/131.jpg'),
('B132','Michael Amoh','Bishop','United Denominations','assets/bishops/matched-132.webp'),
('B251','Michael Asare','Bishop','First Love','assets/bishops/matched-251.webp'),
('B133','Michael Dotsey-Dzokoto','Bishop','United Denominations','assets/bishops/133.jpg'),
('B225','Michael Oddoye','Bishop','First Love','assets/bishops/matched-225.webp'),
('B134','Michael Vengkomwine Tengabo','Bishop','United Denominations','assets/bishops/134.jpg'),
('B333','Miranda Siweya','Mother','Outreach','assets/pastors/verified-3127.webp'),
('B135','Moro Martin-Luther Okoh','Bishop','United Denominations','assets/bishops/135.jpg'),
('B136','Morrison Addo','Bishop','United Denominations','assets/bishops/matched-136.webp'),
('B227','Nana Kwasi Mensah','Bishop','First Love','assets/bishops/matched-227.webp'),
('B137','Napoleon Essien','Bishop','United Denominations','assets/bishops/matched-137.webp'),
('B138','Nassib Hage','Bishop','United Denominations','assets/bishops/matched-138.webp'),
('B139','Nelson Agbemava','Bishop','United Denominations','assets/bishops/139.jpg'),
('B140','Nelson Tika','Bishop','United Denominations','assets/bishops/matched-140.webp'),
('B334','Nely Nina Masuku','Mother','Outreach','assets/outreach/confirmed-334.jpg'),
('B325','Nii Adjeidu Armar','Bishop','United Denominations','assets/bishops/confirmed-325.jpeg'),
('B142','Noble Nobleson','Bishop','United Denominations','assets/bishops/matched-142.webp'),
('B143','Norman Kwadwo Darkwa','Bishop','United Denominations','assets/bishops/143.jpg'),
('B144','Okereke Peter Chibuzor','Bishop','United Denominations','assets/bishops/144.jpg'),
('B145','Olivia Kofi-Opata','Episcopal Sister','United Denominations','assets/bishops/matched-145.webp'),
('B146','Oreal Valerius Lartey','Bishop','United Denominations','assets/bishops/146.jpg'),
('B147','Otonye Alba Bassey Ekefre','Episcopal Sister','United Denominations','assets/bishops/matched-147.webp'),
('B148','Paa Kwesi Nyarkoh','Bishop','United Denominations','assets/bishops/matched-148.webp'),
('B149','Pamela Marnette Dickson','Episcopal Sister','United Denominations','assets/bishops/matched-149.webp'),
('B151','Paschal Kow Dadzie Godwyll','Bishop','United Denominations','assets/bishops/matched-151.webp'),
('B152','Patrick Bruce','Bishop','United Denominations','assets/bishops/matched-152.webp'),
('B228','Patrick Inkoom','Bishop','First Love','assets/bishops/matched-228.webp'),
('B229','Paul Ackuaku','Bishop','First Love','assets/bishops/matched-229.webp'),
('B153','Paul Anaba Mbah','Bishop','United Denominations','assets/bishops/reconciled-153.webp'),
('B230','Paul Baidoo','Bishop','First Love','assets/bishops/matched-230.webp'),
('B154','Peter Mokganya','Bishop','United Denominations','assets/bishops/matched-154.webp'),
('B249','Peter Onasis','Bishop','First Love','assets/bishops/matched-249.webp'),
('B155','Philip Asante','Bishop','United Denominations','assets/bishops/matched-155.webp'),
('B156','Phillippa-Marka Coker','Episcopal Sister','United Denominations','assets/bishops/matched-156.webp'),
('B336','Pius Worlano','Bishop','Outreach','assets/outreach/pius-user-confirmed.jpg'),
('B157','Prince Charles Addae','Bishop','Outreach','assets/bishops/matched-157.webp'),
('B158','Prince Samuel Osei','Bishop','First Love','assets/bishops/matched-158.webp'),
('B330','Randy Mills-Thompson','Bishop','Outreach','assets/outreach/confirmed-330.jpeg'),
('B159','Ransford Owusu','Bishop','United Denominations','assets/bishops/matched-159.webp'),
('B160','Raphael Mendes Essien','Bishop','United Denominations','assets/bishops/160.jpg'),
('B161','Raymond Amarkyne','Bishop','United Denominations','assets/bishops/matched-161.webp'),
('B162','Raymond Mensah','Bishop','United Denominations','assets/bishops/matched-162.webp'),
('B163','Raymond Stephens','Bishop','United Denominations','assets/bishops/matched-163.webp'),
('B164','Rebecca Joana Addae','Episcopal Sister','United Denominations','assets/bishops/matched-164.webp'),
('B165','Reginald Agyir Dadzie','Bishop','First Love',''),
('B250','Reginald Sarkodie','Bishop','First Love','assets/bishops/matched-250.webp'),
('B166','Richard Afenyo Tsaku','Bishop','United Denominations','assets/bishops/matched-166.webp'),
('B167','Richard Aryee','Bishop','United Denominations','assets/bishops/matched-167.webp'),
('B168','Richard Gyamena','Bishop','United Denominations','assets/bishops/matched-168.webp'),
('B169','Richard Nii Okai Aryee','Bishop','First Love','assets/bishops/matched-169.webp'),
('B170','Robert Amanquanor','Bishop','United Denominations','assets/bishops/170.jpg'),
('B171','Robert Dodoo','Bishop','United Denominations','assets/bishops/matched-171.webp'),
('B172','Robert Okai Nunoo','Bishop','United Denominations','assets/bishops/matched-172.webp'),
('B173','Rodino Daniel Nhabanga','Bishop','United Denominations','assets/bishops/reconciled-173.webp'),
('B235','Roger Hiltbrunner','Bishop','First Love','assets/bishops/matched-235.webp'),
('B174','Romeo Sosu','Bishop','United Denominations','assets/bishops/matched-174.webp'),
('B175','Rory Aryee','Bishop','United Denominations','assets/bishops/matched-175.webp'),
('B236','Rudy Vaye','Bishop','First Love','assets/bishops/matched-236.webp'),
('B237','Rutendo Mantiziba','Bishop','First Love','assets/bishops/matched-237.webp'),
('B176','Sampson Kweku Kissi','Bishop','United Denominations','assets/bishops/matched-176.webp'),
('B177','Samuel Kwame Gasper','Bishop','United Denominations','assets/bishops/matched-177.webp'),
('B178','Samuel Obeng','Bishop','United Denominations','assets/bishops/matched-178.webp'),
('B179','Sara Lanita Obuobisa','Episcopal Sister','United Denominations','assets/bishops/matched-179.webp'),
('B180','Selasy Mcsaint','Bishop','United Denominations','assets/bishops/matched-180.webp'),
('B181','Sena Agyepong','Bishop','First Love','assets/bishops/matched-181.webp'),
('B182','Simone-Pierre Eyra Ademola','Mother','First Love','assets/bishops/matched-182.webp'),
('B183','Solomon Boateng','Bishop','United Denominations','assets/bishops/matched-183.webp'),
('B240','Solomon Tay','Bishop','First Love','assets/bishops/matched-240.webp'),
('B241','Stephen Jaiden Asamoah','Bishop','First Love','assets/bishops/matched-241.webp'),
('B184','Stephen Poku','Bishop','United Denominations','assets/bishops/matched-184.webp'),
('B185','Tennyson Ojeisekhoba','Bishop','United Denominations','assets/bishops/matched-185.webp'),
('B242','Terry Bartels','Bishop','First Love','assets/bishops/matched-242.webp'),
('B244','Tomi Njoku','Bishop','First Love','assets/bishops/matched-244.webp'),
('B321','Toss Mills-Odoi','Bishop','United Denominations','assets/bishops/confirmed-321.jpeg'),
('B186','Victor Collins Asabere','Bishop','United Denominations','assets/bishops/matched-186.webp'),
('B187','Vivaldi-Joy Aboagye','Mother','First Love','assets/bishops/matched-187.webp'),
('B188','William Ato Wilson','Bishop','United Denominations','assets/bishops/matched-188.webp'),
('B189','Wisdom Felix Ahiagah','Bishop','United Denominations','assets/bishops/189.jpg'),
('B190','Wisdom Kwesi Eli Tsyi','Bishop','United Denominations','assets/bishops/matched-190.webp'),
('B191','Wisdom Nii Lartey Adams','Bishop','United Denominations','assets/bishops/matched-191.webp'),
('B192','Xola Mpupu','Bishop','United Denominations','assets/bishops/matched-192.webp'),
('B193','Zoe-Andria Asamoah','Mother','First Love','assets/bishops/matched-193.webp')
ON CONFLICT(id) DO NOTHING;
