export const DENOMINATIONS = {
  "First Love": [
    "First Love Church",
    "La Belle Eglise",
    "Go Ye Church",
    "Go Church",
    "Jesus Gefunden",
    "Bénédiction Totale",
    "Mustard Seed Chapel International",
    "Qodesh Family Church",
  ],
  "United Denominations": [
    "1000 Micro Church Network International",
    "American Missionary Church",
    "Amour Internationale",
    "Anagkazo Assemblies",
    "Bema International Church",
    "Candle In The Dark Church",
    "Castle City Church",
    "Catch The Anointing Centre",
    "Double Mega Missionary Church",
    "East End City Churches",
    "East Mountain Churches",
    "Eglise Benediction Totale",
    "Eschatos",
    "Ethiopia",
    "Everything By Prayer Center",
    "Fruitferos Internacional Guinea Bissau",
    "Go Church",
    "Good Shepherd Church Guyana",
    "Greater Love Church Ghana",
    "It Is A Great Thing To Serve The Lord",
    "Jesus Gefunden",
    "Jesus Is The Answer Church",
    "Jesus Is The Door",
    "Jesus Is The Rock Church",
    "Jesus Saviour Of The World Church International",
    "La Belle Eglise Gabon",
    "Laikos International Church",
    "Lighthouse Chapel International",
    "Lighthouse City Churches",
    "Living Waters International",
    "Loyalty House International",
    "Makarios City Church",
    "Makarios Western North",
    "Malawi",
    "Mustard Seed Chapel International",
    "Onction Internationale Benin",
    "Others International Church",
    "Pleasant Surprise",
    "Poimano Internacional Nicaragua",
    "Poimen Church Senegal-Gambia",
    "Precious Souls Namibia",
    "Precious Souls Swaziland",
    "Premiero Amor",
    "Primeiras Obras",
    "Qodesh City Churches",
    "Qodesh Family Churches",
    "Rejoice Greatly",
    "Rencontre Prophetique Internationale",
    "Revelation Church Of Asia",
    "Revival International",
    "Sagesse Internationale Guinea",
    "Savior Of Men International",
    "Saviours Of Men International",
    "Serious Christian Church",
    "Shepherd House International",
    "Strait Gate Church Liberia",
    "Strong Christian Church",
    "Talanta International Tanzania",
    "The Glorious Church",
    "The Machaneh Church International",
    "The Makarios Church",
    "The Mega Church",
    "Victoire Internationale",
    "West End City Churches",
    "Australia",
    "United Cities",
    "Burkina Faso",
    "Cape Verde",
    "Central African Republic",
    "Chad",
    "Equatorial Guinea",
    "Fiji",
    "Gambia",
    "Guinea",
    "Lesotho",
    "Mali",
    "New Zealand",
    "Niger",
    "Papua New Guinea",
    "Samoa",
    "Sao Tome And Principe",
    "Solomon Islands",
    "Tonga",
    "Vanuatu",
  ],
  DHMM: [],
  FLOW: [],
  "HJC": [],
};
