// Generated by scripts/build-roll.mjs from the Bishops List and the bishops' sheets. Do not edit by hand.
export const GROUPS = {
  "UD Ghana": {
    "organization": "United Denominations",
    "denominations": [
      "Anagkazo Assemblies",
      "Castle City Church",
      "East End City Churches",
      "East Mountain Churches",
      "Jesus Is The Rock Church",
      "Jesus Saviour Of The World Church International",
      "Lighthouse Chapel International",
      "Lighthouse City Churches",
      "Loyalty House Internatioanal",
      "Makarios City Church",
      "Makarios City Churh",
      "Makarios Western North",
      "Qodesh Family Churches",
      "Saviours Of Men International",
      "The Glorious Mega Church",
      "The Glorious Megachurch",
      "The Machaneh Church International",
      "The Makarios Church",
      "The Mega Church",
      "West End City Churches"
    ]
  },
  "UD Africa": {
    "organization": "United Denominations",
    "denominations": [
      "1000 Micro Church Network International",
      "Amour Internationale",
      "Bema International Church",
      "Double Mega Missionary Church",
      "Everything By Prayer Center",
      "Firstlove Church",
      "Flc, Malawi",
      "Fruitferos Internacional Guinea Bissau",
      "Fruitiferos Internationale",
      "La Belle Eglise Gabon",
      "La Belle Église Car",
      "Libreville City State",
      "Onction Internationale Benin",
      "Poimen Church Gambia",
      "Poimen Church Senegal-Gambia",
      "Praia City State Church",
      "Precious Souls Church – Eswatini",
      "Precious Souls Namibia",
      "Precious Souls Swaziland",
      "Premiero Amor",
      "Primeiras Obras",
      "Primero Amor",
      "Rencontre Prophetique Internationale",
      "Sagesse Internationale Guinea",
      "Serious Christian Church",
      "Serious Christian Church Lesotho",
      "Strait Gate Church Liberia",
      "Strong Christian Christian",
      "Strong Christian Chruch",
      "Strong Christian Church",
      "Strong Christian Church (Udaf)",
      "Strong Christian Church L",
      "Strong Christian Church South Africa",
      "Talanta International Tanzania",
      "United Cities",
      "Victoire Internationale"
    ]
  },
  "UD Europe": {
    "organization": "United Denominations",
    "denominations": [
      "Candle In The Dark Church",
      "It Is A Great Thing To Serve The Lord",
      "Jesus Gefunden",
      "Living Waters International",
      "Mustard Seed Chapel International",
      "Pleasant Surprise",
      "Rose Of Sharon",
      "Tell Them Church"
    ]
  },
  "UD North America": {
    "organization": "United Denominations",
    "denominations": [
      "American Missionary Church",
      "Laikos International Church",
      "Rejoice Greatly",
      "Revival International"
    ]
  },
  "United Islands": {
    "organization": "United Denominations",
    "denominations": [
      "Favourite Child Church",
      "Pacific Islands Missionary Church",
      "United Islands"
    ]
  },
  "United Jesus": {
    "organization": "United Denominations",
    "denominations": [
      "Jesus Is The Answer Church",
      "Jesus Is The Door",
      "Jesus Is The Master"
    ]
  },
  "Eschatos": {
    "organization": "United Denominations",
    "denominations": [
      "Eschatos"
    ]
  },
  "Reasonable Service": {
    "organization": "United Denominations",
    "denominations": [
      "Allos Mega Church",
      "Anointed People International",
      "Anointed Word Chapel Int",
      "Glory Life Hope Center",
      "Keep My Word Chapel International",
      "The Mega Church – Grace Chapel",
      "The Mega Church – Nachal Cathedral",
      "True Son Chapel International"
    ]
  }
};
