// Generated by scripts/build-reference.mjs from data/official-bishops.json. Do not edit by hand.
export const GROUPS = {
  "UD Ghana": {
    "organization": "United Denominations",
    "denominations": [
      "The Makarios Church",
      "Makarios Western North",
      "Jesus Saviour Of The World Church International",
      "Qodesh Family Churches",
      "The Mega Church",
      "East End City Churches",
      "Castle City Church",
      "The Machaneh Church International",
      "Lighthouse Chapel International",
      "Loyalty House International",
      "Makarios City Church",
      "Jesus Is The Rock Church",
      "Lighthouse City Churches",
      "The Glorious Church",
      "Anagkazo Assemblies",
      "East Mountain Churches",
      "West End City Churches",
      "Qodesh City Churches",
      "United Cities"
    ]
  },
  "UD Africa": {
    "organization": "United Denominations",
    "denominations": [
      "1000 Micro Church Network International",
      "Bema International Church",
      "Double Mega Missionary Church",
      "Everything By Prayer Center",
      "Onction Internationale Benin",
      "Fruitferos Internacional Guinea Bissau",
      "Primeiras Obras",
      "Rencontre Prophetique Internationale",
      "Serious Christian Church",
      "Strait Gate Church Liberia",
      "Strong Christian Church",
      "Malawi",
      "Talanta International Tanzania",
      "Premiero Amor",
      "La Belle Eglise Gabon",
      "Others International Church",
      "Victoire Internationale",
      "Poimen Church Senegal-Gambia",
      "Guinea",
      "Amour Internationale",
      "Precious Souls Namibia",
      "Precious Souls Swaziland",
      "Central African Republic",
      "Equatorial Guinea",
      "Cape Verde",
      "Lesotho",
      "Burkina Faso",
      "Seychelles",
      "United Cities"
    ]
  },
  "UD Europe": {
    "organization": "United Denominations",
    "denominations": [
      "Candle In The Dark Church",
      "Jesus Gefunden",
      "Mustard Seed Chapel International",
      "Pleasant Surprise",
      "It Is A Great Thing To Serve The Lord",
      "Go Church"
    ]
  },
  "UD North America": {
    "organization": "United Denominations",
    "denominations": [
      "Revival International",
      "American Missionary Church",
      "Rejoice Greatly",
      "Laikos International Church"
    ]
  },
  "United Islands": {
    "organization": "United Denominations",
    "denominations": [
      "Favourite Child Church",
      "Good Shepherd Church Guyana",
      "United Cities"
    ]
  },
  "United Jesus": {
    "organization": "United Denominations",
    "denominations": [
      "Jesus Is The Answer Church",
      "Jesus Is The Door",
      "Castle City Church",
      "United Cities"
    ]
  },
  "Eschatos": {
    "organization": "United Denominations",
    "denominations": [
      "Eschatos"
    ]
  },
  "Reasonable Service": {
    "organization": "United Denominations",
    "denominations": [
      "The Machaneh Church International",
      "Allos Mega Church",
      "Others International Church",
      "Loyalty House International",
      "The Mega Church",
      "Anointed Word Chapel Int",
      "Shepherd House International"
    ]
  }
};
