// Generated by scripts/build-reference.mjs from data/official-bishops.json. Do not edit by hand.
export const GROUPS = {
  "UD Ghana": {
    "organization": "United Denominations",
    "denominations": [
      "Makarios Church",
      "Makarios Western North",
      "Jesus Saviour of the World Church",
      "Qodesh Family Church",
      "The Mega Church",
      "East End City Church",
      "Castle City Church",
      "Machaneh Church Int",
      "The Machaneh Church",
      "Lighthouse Chapel International",
      "Loyalty House Internatioanal",
      "Makarios City Church",
      "Jesus is the Rock Church",
      "Lighthouse City Church",
      "The Glorious Mega Church",
      "Anagkazo Assemblies",
      "East Mountain Church",
      "West End City Church",
      "Qodesh City Church"
    ]
  },
  "UD Africa": {
    "organization": "United Denominations",
    "denominations": [
      "1000 Micro Church Network",
      "Bema International",
      "Double Mega Missionary Church",
      "Everything By Prayer Church",
      "Onction Internationale",
      "Fruitiferos Internationale",
      "Primeiras Obras",
      "Rencontre Prophetique Internationale",
      "Serious Christian Church",
      "Strait Gate Church",
      "Strong Christian Church",
      "Malawi",
      "Talanta International",
      "Primero Amor",
      "Gabon – Libreville",
      "Gabon – Port Gentil",
      "Other International",
      "Congo Brazaville",
      "Poimen Church - Senegal",
      "Guinea Conakry",
      "Amour International",
      "Precious Souls Church – Namibia",
      "Precious Souls Church – Eswatini",
      "Central African Republic",
      "Poimen Church Gambia",
      "Equatorial Guinea( Malabo)",
      "Cape Verde",
      "Equatorial Guinea (Bata)",
      "Lesotho",
      "Burkina Faso",
      "Seychelles"
    ]
  },
  "UD Europe": {
    "organization": "United Denominations",
    "denominations": [
      "Candle In The Dark",
      "Jesus Gefunden",
      "Mustard Seed Chapel",
      "Pleasant Surprise Church",
      "It Is A Great Thing To Serve The Lord",
      "Go Church"
    ]
  },
  "UD North America": {
    "organization": "United Denominations",
    "denominations": [
      "Revival International",
      "American Missionary Church",
      "Rejoice Greatly",
      "Laikos"
    ]
  },
  "United Islands": {
    "organization": "United Denominations",
    "denominations": [
      "PACIFIC ISLANDS MISSIONARY CHURCH- Fiji",
      "PACIFIC ISLANDS MISSIONARY CHURCH- Solomon Islands",
      "PACIFIC ISLANDS MISSIONARY CHURCH- Papau New Guinea",
      "Favourite Child Church",
      "PACIFIC ISLANDS MISSIONARY CHURCH- Vanuatu",
      "Suriname"
    ]
  },
  "United Jesus": {
    "organization": "United Denominations",
    "denominations": [
      "Jesus is The Answer",
      "Jesus is the Door",
      "Jesus is The Master"
    ]
  },
  "Eschatos": {
    "organization": "United Denominations",
    "denominations": [
      "Eschatos"
    ]
  },
  "Reasonable Service": {
    "organization": "United Denominations",
    "denominations": [
      "Anointed People International",
      "Allos Mega Church",
      "Keep My Word Chapel International",
      "True Son Chapel International",
      "The Mega Church – Grace Chapel",
      "The Mega Church – Nachal Cathedral",
      "Anointed Word Chapel Int",
      "Glory Life Hope Center"
    ]
  }
};
