// The four PDFs for the office after a roll build (scripts/build-roll.mjs):
//  01 Bishops with no sheet · 02 Unclaimed pastors by group · 03 Conflicts with the sheet rows as evidence · 04 Pastors without a photo (compact) · 05 Possible duplicates (scripts/scan-duplicates.mjs)
import { readFileSync, existsSync, mkdirSync } from 'node:fs';
import { chromium } from 'playwright';
import sharp from 'sharp';
import { placeOf, titleFor, bySurname } from '../src/registration/model.mjs';
const root = new URL('..', import.meta.url).pathname;
const people = JSON.parse(readFileSync(`${root}src/registration/reference-people.json`, 'utf8'));
const report = JSON.parse(readFileSync(`${root}data/reports/roll-build.json`, 'utf8'));
const OUT = `${process.env.HOME}/Downloads/Kuriake Castle Project/02 Deliverables for the office`;
mkdirSync(`${root}.tmp-checks/pdfthumbs`, { recursive: true });
const pending = [];
const thumb = (p) => { if (!p.image || !existsSync(`${root}${p.image}`)) return ''; const t = p.image.replace(/^(assets\/(?:portraits|bishops|pastors))\/([^/]+)\.[^.]+$/, '$1/thumbs/$2.webp'); const src = `${root}${existsSync(`${root}${t}`) ? t : p.image}`; const out = `.tmp-checks/pdfthumbs/${p.id}.jpg`; pending.push(existsSync(`${root}${out}`) ? null : sharp(src).resize({ width: 180, withoutEnlargement: true }).jpeg({ quality: 72 }).toFile(`${root}${out}`).catch(() => {})); return `http://localhost:4301/${out}`; };
const esc = (s) => String(s ?? '').replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
const img = (p) => thumb(p) ? `<img src="${thumb(p)}">` : '<div class="nophoto">no photo</div>';
const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }) + ', ' + new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }); // generated at
const css = `@page { size: A4; margin: 14mm 12mm; } body { font-family: -apple-system, "Helvetica Neue", Arial, sans-serif; color: #13324c; font-size: 10.5px; }
  .cover { height: 250mm; display: flex; flex-direction: column; justify-content: center; text-align: center; page-break-after: always; } .cover h1 { font-size: 40px; margin: 0 0 10px; line-height: 1.05; } .cover h1 small { display: block; font-size: 14px; letter-spacing: .3em; color: #6a7283; margin-bottom: 14px; } .cover p { max-width: 580px; margin: 8px auto; color: #425466; font-size: 13px; line-height: 1.5; }
  .cover table { margin: 24px auto 0; border-collapse: collapse; font-size: 12.5px; } .cover td { padding: 5px 16px; border-bottom: 1px solid #dfe6f3; text-align: left; } .cover td:last-child { text-align: right; font-weight: 700; }
  .group { page-break-before: always; } .group h1 { font-size: 20px; margin: 0 0 2px; } .count { margin: 0 0 8px; color: #6a7283; font-size: 12px; } .why { margin: 0 0 12px; padding: 8px 10px; background: #fff7f6; border: 1px solid #f3b4ae; border-radius: 8px; font-size: 11px; line-height: 1.45; }
  table.b { width: 100%; border-collapse: collapse; } table.b th { text-align: left; font-size: 9.5px; color: #6a7283; padding: 3px 5px; border-bottom: 1px solid #c9d3e6; } table.b td { padding: 4px 5px; border-bottom: 1px solid #e7ecf5; vertical-align: middle; } table.b tr { page-break-inside: avoid; }
  table.b img, table.b .nophoto { width: 46px; height: 58px; object-fit: cover; border-radius: 5px; background: #e6ece9; display: flex; align-items: center; justify-content: center; font-size: 8px; color: #8a94a6; } .muted { color: #6a7283; }
  .conf { page-break-inside: avoid; border: 1px solid #e7ecf5; border-radius: 10px; padding: 8px 10px 10px; margin: 0 0 10px; } .conf h3 { margin: 0 0 6px; font-size: 13px; } .claim { margin: 6px 0; padding: 6px 8px; background: #f6f8fb; border-radius: 6px; } .claim b { color: #13324c; } .cells { font-family: Menlo, monospace; font-size: 9px; color: #425466; display: block; margin-top: 3px; white-space: pre-wrap; } .claim .src { font-size: 9.5px; color: #6a7283; }
  .compact { columns: 2; column-gap: 14px; font-size: 9.5px; } .compact div { break-inside: avoid; padding: 2px 0; border-bottom: 1px solid #eef2f7; } .compact b { font-size: 10px; }`;
const page = (title, intro, rows, body) => `<!doctype html><html><head><meta charset="utf-8"><style>${css}</style></head><body><div class="cover"><h1><small>KURIAKE CASTLE</small>${title}</h1><p>${intro}</p><table>${rows.map(([k, v]) => `<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join('')}</table><p style="margin-top:28px;color:#8a94a6">Generated ${date}</p></div>${body}</body></html>`;
const render = async (html, name) => { await Promise.all(pending.filter(Boolean)); pending.length = 0; const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' }); const pg = await browser.newPage(); await pg.setContent(html, { waitUntil: 'networkidle', timeout: 300000 }); await pg.emulateMedia({ media: 'print' }); const out = `${OUT}/${name}.pdf`; await pg.pdf({ path: out, format: 'A4', printBackground: true, displayHeaderFooter: true, headerTemplate: '<span></span>', footerTemplate: `<div style="width:100%;text-align:center;font-size:9px;color:#8a94a6;font-family:Arial">Kuriake Castle · ${esc(name.replace(/^\d+ /, ''))} · page <span class="pageNumber"></span> of <span class="totalPages"></span></div>`, margin: { top: '14mm', bottom: '16mm', left: '12mm', right: '12mm' } }); await browser.close(); console.log('written', name); };
const bishops = people.filter((p) => p.role === 'bishop' && p.title !== 'Lay President'), pastors = people.filter((p) => p.role === 'pastor');
// ---- 01 Bishops with no sheet
const noSheet = report.noSheet.map((n) => ({ ...n, rec: bishops.find((b) => b.id === n.id) || {} }));
const rowB = (n) => `<tr><td>${img(n.rec)}</td><td><b>${esc(n.rec.name || n.listName)}</b><br><span class="muted">${esc(n.listName)} on the Bishops List</span></td><td>${esc(n.group)}</td><td>${esc(n.denomination || '-')}</td><td>${esc(n.branch || '-')}</td></tr>`;
const intro01 = 'Bishops on the office’s Bishops List (9 October 2026) for whom no sheet was received: not in the folder of bishops with pastors, not in the folder of bishops with no pastors, and not one of the two known outstanding (Bishop Kent Njeru, Bishop Toss Mills-Odoi). Until a sheet arrives they have no pastors on the roll.';
const body01 = `<section class="group"><h1>No sheet received</h1><p class="count">${noSheet.length} bishops</p><table class="b"><thead><tr><th>Photo</th><th>Name</th><th>Group</th><th>Denomination / country</th><th>Branch</th></tr></thead><tbody>${noSheet.map(rowB).join('')}</tbody></table></section>`;
const body01b = report.sheetsNotOnList.length ? `<section class="group"><h1>Sheets from people who are not on the Bishops List</h1><p class="count">${report.sheetsNotOnList.length} sheets</p><table class="b"><thead><tr><th>Name on the sheet</th><th>File</th><th>Pastors listed</th></tr></thead><tbody>${report.sheetsNotOnList.map((x) => `<tr><td><b>${esc(x.bishop)}</b></td><td>${esc(x.file)}</td><td>${x.noPastors ? 'says none' : x.pastors}</td></tr>`).join('')}</tbody></table><p class="why">Their pastors are on the roll as Unclaimed with the name kept, until the office says which bishop they belong to or adds the person to the Bishops List.</p></section>` : '';
await render(page('BISHOPS WITH<br>NO SHEET', intro01, [['Bishops on the list', bishops.length], ['Sheets received', report.totals.sheets], ['Bishops covered by a sheet', report.totals.bishopsWithSheet], ['Say they have no pastors', report.totals.noPastorsSheets], ['Outstanding, known', 2], ['No sheet at all', noSheet.length]], body01 + body01b), '01 Bishops with no sheet');
// ---- 02 Unclaimed by group
const unclaimed = pastors.filter((p) => p.unclaimed);
const groupsU = [...new Set(unclaimed.map((p) => p.group || p.organization || 'No group'))].sort();
const rowP = (p) => `<tr><td>${img(p)}</td><td><b>${esc(p.name)}</b><br><span class="muted">${esc(titleFor(p))}</span></td><td>${esc(p.denomination || '-')}</td><td>${esc(placeOf(p) || '-')}</td><td>${esc(p.unclaimed)}</td></tr>`;
await render(page('UNCLAIMED PASTORS', 'Pastors on the sheets whom the system could not place under one bishop: named on two bishops’ sheets with no ruling yet, or listed on a sheet from someone who is not on the Bishops List. They are off the public directory until the office decides. Grouped by church group.', [['Unclaimed pastors', unclaimed.length], ['Claimed by two bishops', unclaimed.filter((p) => /^Claimed by/.test(p.unclaimed)).length], ['Listed by someone not on the Bishops List', unclaimed.filter((p) => /^Listed by/.test(p.unclaimed)).length]], groupsU.map((g) => { const list = unclaimed.filter((p) => (p.group || p.organization || 'No group') === g).sort(bySurname); return `<section class="group"><h1>${esc(g)}</h1><p class="count">${list.length} pastors</p><table class="b"><thead><tr><th>Photo</th><th>Name</th><th>Denomination</th><th>Place</th><th>Why unclaimed</th></tr></thead><tbody>${list.map(rowP).join('')}</tbody></table></section>`; }).join('')), '02 Unclaimed pastors by group');
// ---- 03 Conflicts with evidence
const conf = (c) => `<div class="conf"><h3>${esc(c.name)}</h3>${c.claims.map((k) => `<div class="claim"><b>Bishop ${esc(k.bishop)}</b> <span class="muted">· ${esc(k.group || '')}</span><br><span class="src">Sheet “${esc(k.file)}” (${esc(k.folder)}), row ${k.row}</span><span class="cells">${esc(k.cells.join('  |  '))}</span></div>`).join('')}</div>`;
await render(page('PASTORS CLAIMED BY<br>TWO BISHOPS', 'Each person below appears on more than one bishop’s sheet and no ruling from the office covers them yet. For every claim the exact sheet, row number and the row’s own cells are shown (phone numbers and emails blanked) so the office can see who listed whom. The rulings given in the group on 9 October have already been applied and are listed at the end.', [['Still to decide', report.conflicts.length], ['Settled by the group’s rulings', report.resolved.length]], `<section class="group"><h1>To decide</h1><p class="count">${report.conflicts.length} people</p>${report.conflicts.map(conf).join('')}</section><section class="group"><h1>Settled by the rulings of 9 October</h1><p class="count">${report.resolved.length} people</p><table class="b"><thead><tr><th>Pastor</th><th>Placed under</th><th>Removed from</th><th>Ruling</th></tr></thead><tbody>${report.resolved.map((r) => `<tr><td><b>${esc(r.name)}</b></td><td>${esc(r.winner)}</td><td>${esc(r.losers.join(', '))}</td><td class="muted">${esc(r.by)}</td></tr>`).join('')}</tbody></table></section>`), '03 Pastors claimed by two bishops');
// ---- 04 Pastors without a photo (compact)
const noPhoto = pastors.filter((p) => !p.image).sort((a, b) => (a.bishop || '').localeCompare(b.bishop || '') || bySurname(a, b));
const byGroup = [...new Set(noPhoto.map((p) => p.group || p.organization || 'No group'))].sort();
const denomsIn = (g) => [...new Set(noPhoto.filter((p) => (p.group || p.organization || 'No group') === g).map((p) => p.denomination || 'No denomination'))].sort();
await render(page('PASTORS WITHOUT<br>A PHOTO', 'Pastors on the roll with no picture in any photo folder the office has shared and none previously on file. Grouped by church group, then denomination; each line gives the bishop so the picture can be requested.', [['Pastors on the roll', pastors.length], ['With a photo', pastors.length - noPhoto.length], ['Without a photo', noPhoto.length]], byGroup.map((g) => `<section class="group"><h1>${esc(g)}</h1><p class="count">${noPhoto.filter((p) => (p.group || p.organization || 'No group') === g).length} pastors</p><div class="compact">${denomsIn(g).map((d) => { const list = noPhoto.filter((p) => (p.group || p.organization || 'No group') === g && (p.denomination || 'No denomination') === d).sort(bySurname); return `<div><b>${esc(d)}</b> · ${list.length}</div>` + list.map((p) => `<div>${esc(p.name)} <span class="muted">· ${esc(titleFor(p))} · ${esc(p.bishop || 'Unclaimed')}${placeOf(p) ? ' · ' + esc(placeOf(p)) : ''}</span></div>`).join(''); }).join('')}</div></section>`).join('')), '04 Pastors without a photo');

// ---- 05 Possible duplicates (from scripts/scan-duplicates.mjs)
if (existsSync(`${root}data/reports/duplicates-scan.json`)) {
  const scan = JSON.parse(readFileSync(`${root}data/reports/duplicates-scan.json`, 'utf8'));
  const byId = new Map(people.map((p) => [p.id, p]));
  const card = (x) => { const p = byId.get(x.id) || x; return `<div class="card">${img(p)}<b>${esc(x.name)}</b><span>${esc(x.title)}${x.bishop && x.bishop !== '(bishop)' ? ` · under Bishop ${esc(x.bishop)}` : x.bishop === '(bishop)' ? ' · Bishop' : ''}${x.unclaimed ? ' · <i>unclaimed</i>' : ''}</span><span>${esc(x.denomination || x.group || '')}</span><span>${esc(x.place || 'place unknown')}</span><span class="id">${esc(x.id)}</span></div>`; };
  const block = (d) => `<div class="conf ${d.likely ? 'likely' : ''}"><div class="tag">${d.likely ? 'LIKELY THE SAME PERSON' : 'CHECK'} · ${esc(d.reasons.join(' · '))}</div><div class="cards">${d.people.map(card).join('')}</div></div>`;
  const likely = scan.filter((d) => d.likely), check = scan.filter((d) => !d.likely);
  const css5 = `.cards { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; } .card { display: flex; flex-direction: column; gap: 2px; } .card b { font-size: 12px; margin-top: 4px; } .card span { color: #425466; } .card img, .card .nophoto { width: 92px; height: 112px; object-fit: cover; border-radius: 6px; background: #e6ece9; display: flex; align-items: center; justify-content: center; font-size: 9px; color: #8a94a6; } .id { color: #a0a8b8; font-size: 9px; } .conf.likely { border-color: #f3b4ae; background: #fff7f6; } .tag { font-size: 9.5px; font-weight: 700; letter-spacing: .06em; color: #6a7283; margin-bottom: 6px; } .likely .tag { color: #b42318; }`;
  await render(page('POSSIBLE DUPLICATES', 'People who may be one person filed twice: the same picture on two records, the same name, or a name that is a fuller, shorter or respelled form of another’s in the same country, where the birthdays on the sheets do not disagree. Red boxes are almost certainly one person. Tell the office which record to keep.', [['Groups', scan.length], ['Likely the same person', likely.length], ['To check', check.length]], `<style>${css5}</style><section class="group"><h1>Likely the same person</h1><p class="count">${likely.length} groups</p>${likely.map(block).join('')}</section><section class="group"><h1>To check</h1><p class="count">${check.length} groups</p>${check.map(block).join('')}</section>`), '05 Possible duplicates');
}
